export const REQUEST_CARDS = 'REQUEST_CARD';
export const REQUEST_CARDS_SUCCESS = 'REQUEST_CARD_SUCCESS';
export const REQUEST_CARDS_FAILED = 'REQUEST_CARD_FAILED';

export const REQUEST_PAGE_CARDS = 'REQUEST_PAGE_CARDS';
export const REQUEST_PAGE_CARDS_SUCCESS = 'REQUEST_PAGE_CARDS_SUCCESS';
export const REQUEST_PAGE_CARDS_FAILED = 'REQUEST_PAGE_CARDS_FAILED';