export const REQUEST_CARDS = 'REQUEST_CARD';
export const REQUEST_CARDS_SUCCESS = 'REQUEST_CARD_SUCCESS';
export const REQUEST_CARDS_FAILED = 'REQUEST_CARD_FAILED';

export const REQUEST_PAGE_CARDS = 'REQUEST_PAGE_CARDS';
export const REQUEST_PAGE_CARDS_SUCCESS = 'REQUEST_PAGE_CARDS_SUCCESS';
export const REQUEST_PAGE_CARDS_FAILED = 'REQUEST_PAGE_CARDS_FAILED';

export const REQUEST_CARD_DETAIL = 'REQUEST_CARD_DETAIL';
export const REQUEST_CARD_DETAIL_SUCCESS = 'REQUEST_CARD_DETAIL_SUCCESS';
export const REQUEST_CARD_DETAIL_FAILED = 'REQUEST_CARD_DETAIL_FAILED';

export const REQUEST_CARD_TYPES = 'REQUEST_CARD_TYPES';
export const REQUEST_CARD_TYPES_SUCCESS = 'REQUEST_CARD_TYPES_SUCCESS';
export const REQUEST_CARD_TYPES_FAILED = 'REQUEST_CARD_TYPES_FAILED';

export const REQUEST_CARD_SUBTYPES = 'REQUEST_CARD_SUBTYPES';
export const REQUEST_CARD_SUBTYPES_SUCCESS = 'REQUEST_CARD_SUBTYPES_SUCCESS';
export const REQUEST_CARD_SUBTYPES_FAILED = 'REQUEST_CARD_SUBTYPES_FAILED';

export const REQUEST_SEARCH_TYPES_CARDS = 'REQUEST_SEARCH_TYPES_CARDS';
export const REQUEST_SEARCH_TYPES_CARDS_SUCCESS = 'REQUEST_SEARCH_TYPES_CARDS_SUCCESS';
export const REQUEST_SEARCH_TYPES_CARDS_FAILED = 'REQUEST_SEARCH_TYPES_CARDS_FAILED';

export const REQUEST_SEARCH_SUBTYPES_CARDS = 'REQUEST_SEARCH_SUBTYPES_CARDS';
export const REQUEST_SEARCH_SUBTYPES_CARDS_SUCCESS = 'REQUEST_SEARCH_SUBTYPES_CARDS_SUCCESS';
export const REQUEST_SEARCH_SUBTYPES_CARDS_FAILED = 'REQUEST_SEARCH_SUBTYPES_CARDS_FAILED';
